// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TgBot.Exchange;

namespace TgBot.MigrationsPostgres.Exchange
{
    [DbContext(typeof(ExchangeDb))]
    partial class ExchangeDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TgBot.Exchange.AssetType", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<long>("MaxOffer")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("MinOffer")
                        .HasColumnType("bigint");

                    b.Property<long>("MinPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("OneUnit")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("AssetType");

                    b.HasData(
                        new
                        {
                            Key = "USDT",
                            MaxOffer = 1000000L,
                            MaxPrice = 100000000L,
                            MinOffer = 100L,
                            MinPrice = 1L,
                            Name = "Tether",
                            OneUnit = 100L
                        },
                        new
                        {
                            Key = "BTC",
                            MaxOffer = 1000000L,
                            MaxPrice = 100000000L,
                            MinOffer = 100L,
                            MinPrice = 1L,
                            Name = "Bitcoin",
                            OneUnit = 100L
                        },
                        new
                        {
                            Key = "ETH",
                            MaxOffer = 1000000L,
                            MaxPrice = 100000000L,
                            MinOffer = 100L,
                            MinPrice = 1L,
                            Name = "Etherium",
                            OneUnit = 100L
                        });
                });

            modelBuilder.Entity("TgBot.Exchange.BankAccountType", b =>
                {
                    b.Property<string>("BankId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("SingleTransactionAmountLimit")
                        .HasColumnType("bigint");

                    b.Property<long?>("WeeklyTransactionAmountLimit")
                        .HasColumnType("bigint");

                    b.Property<int?>("WeeklyTransactionCountLimit")
                        .HasColumnType("integer");

                    b.HasKey("BankId");

                    b.ToTable("BankAccountType");

                    b.HasData(
                        new
                        {
                            BankId = "CBE",
                            Name = "Commercial Bank of Ethiopia",
                            SingleTransactionAmountLimit = -1L,
                            WeeklyTransactionAmountLimit = -1L,
                            WeeklyTransactionCountLimit = -11
                        },
                        new
                        {
                            BankId = "ABYS",
                            Name = "Commercial Bank of Ethiopia",
                            SingleTransactionAmountLimit = -1L,
                            WeeklyTransactionAmountLimit = -1L,
                            WeeklyTransactionCountLimit = -11
                        },
                        new
                        {
                            BankId = "DASH",
                            Name = "Dashen Bank",
                            SingleTransactionAmountLimit = -1L,
                            WeeklyTransactionAmountLimit = -1L,
                            WeeklyTransactionCountLimit = -11
                        },
                        new
                        {
                            BankId = "CBO",
                            Name = "Cooperative Bank of Oromia",
                            SingleTransactionAmountLimit = -1L,
                            WeeklyTransactionAmountLimit = -1L,
                            WeeklyTransactionCountLimit = -11
                        },
                        new
                        {
                            BankId = "HBR",
                            Name = "Bibret Bank",
                            SingleTransactionAmountLimit = -1L,
                            WeeklyTransactionAmountLimit = -1L,
                            WeeklyTransactionCountLimit = -11
                        },
                        new
                        {
                            BankId = "ZMN",
                            Name = "Zemen Bank",
                            SingleTransactionAmountLimit = -1L,
                            WeeklyTransactionAmountLimit = -1L,
                            WeeklyTransactionCountLimit = -11
                        });
                });

            modelBuilder.Entity("TgBot.Exchange.ExchangeOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("AssetKey")
                        .HasColumnType("text");

                    b.Property<Guid>("CreateTranId")
                        .HasColumnType("uuid");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("StatusTime")
                        .HasColumnType("bigint");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UpdateTranId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ExchangeOffer");
                });

            modelBuilder.Entity("TgBot.Exchange.ExchangeTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionType")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExchangeTransaction");
                });

            modelBuilder.Entity("TgBot.Exchange.ExchangeTransactionData", b =>
                {
                    b.Property<Guid>("TranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.HasKey("TranId");

                    b.ToTable("ExchangeTransactionData");
                });

            modelBuilder.Entity("TgBot.Exchange.ExchangeUserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EMail")
                        .HasColumnType("text");

                    b.Property<bool>("EmailVarified")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<Guid>("TranId")
                        .HasColumnType("uuid");

                    b.Property<int>("UserStatus")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("ExchangeUserProfile");
                });

            modelBuilder.Entity("TgBot.Exchange.OfferBankAccount", b =>
                {
                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankId")
                        .HasColumnType("text");

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("OfferId", "BankId");

                    b.ToTable("OfferBankAccount");
                });

            modelBuilder.Entity("TgBot.Exchange.OfferStatusHistory", b =>
                {
                    b.Property<Guid>("TranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<int>("OldStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PrevTranId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<int>("SeqNo")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("TranId");

                    b.ToTable("OfferStatusHistory");
                });

            modelBuilder.Entity("TgBot.Exchange.TrusteeApplication", b =>
                {
                    b.Property<Guid>("TranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UpdateTranId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("TranId");

                    b.ToTable("TrusteeApplication");
                });

            modelBuilder.Entity("TgBot.Exchange.TrusteeBankAccount", b =>
                {
                    b.Property<Guid>("TrusteId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankId")
                        .HasColumnType("text");

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.HasKey("TrusteId", "BankId");

                    b.ToTable("TrusteeBankAccount");
                });

            modelBuilder.Entity("TgBot.Exchange.TrusteeInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreateTranId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateTranId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrusteeInformation");
                });

            modelBuilder.Entity("TgBot.SmartLedger.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Operation")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentRecord")
                        .HasColumnType("uuid");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditRecord");
                });

            modelBuilder.Entity("TgBot.SmartLedger.CashEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<Guid?>("TransactionHead")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CashEntity");
                });

            modelBuilder.Entity("TgBot.SmartLedger.MisDelta", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("DataType")
                        .HasColumnType("text");

                    b.Property<long>("RecordNo")
                        .HasColumnType("bigint");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("AuditId");

                    b.ToTable("MisDelta");
                });

            modelBuilder.Entity("TgBot.SmartLedger.MisUserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("Permitted")
                        .HasColumnType("boolean");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("MisUserProfile");
                });

            modelBuilder.Entity("TgBot.Workflow.WorkFlowInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("WorkItemHead")
                        .HasColumnType("uuid");

                    b.Property<long?>("WorkItemHeadTime")
                        .HasColumnType("bigint");

                    b.Property<int?>("WorkItemHeadType")
                        .HasColumnType("integer");

                    b.Property<int>("WorkType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkFlowInfo");
                });

            modelBuilder.Entity("TgBot.Workflow.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("PrevItem")
                        .HasColumnType("uuid");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkFlowId")
                        .HasColumnType("uuid");

                    b.Property<int>("WorkType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkItem");
                });
#pragma warning restore 612, 618
        }
    }
}
