// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TgBot.TgDb;

namespace TgBot.MigrationsPostgres.TgBotContext
{
    [DbContext(typeof(TgBotDbContext))]
    [Migration("20260102013949_InitPostgres")]
    partial class InitPostgres
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TgBot.JoinedTGGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BotId")
                        .HasColumnType("text");

                    b.Property<long>("JoinedTime")
                        .HasColumnType("bigint");

                    b.Property<long>("LeftTime")
                        .HasColumnType("bigint");

                    b.Property<long>("TgGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("JoinedTGGroup");
                });

            modelBuilder.Entity("TgBot.TgUserState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<long>("LastUpdateTime")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("StackHead")
                        .HasColumnType("uuid");

                    b.Property<string>("TgBotId")
                        .HasColumnType("text");

                    b.Property<string>("TgUserID")
                        .HasColumnType("text");

                    b.Property<bool>("WaitingForPayment")
                        .HasColumnType("boolean");

                    b.Property<string>("WbcCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TgUserState");
                });

            modelBuilder.Entity("TgBot.WFDialogItem", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BotId")
                        .HasColumnType("text");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("DataType")
                        .HasColumnType("text");

                    b.Property<Guid?>("Next")
                        .HasColumnType("uuid");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean");

                    b.Property<string>("TgUserId")
                        .HasColumnType("text");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("WFDialogStack");
                });
#pragma warning restore 612, 618
        }
    }
}
