// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TgBot.TgDb;

namespace TgBot.Migrations
{
    [DbContext(typeof(TgBotDbContext))]
    [Migration("20210622191132_change_6_22")]
    partial class change_6_22
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TgBot.JoinedTGGroup", b =>
                {
                    b.Property<long>("TgGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("JoinedTime")
                        .HasColumnType("bigint");

                    b.Property<long>("LeftTime")
                        .HasColumnType("bigint");

                    b.HasKey("TgGroupId");

                    b.ToTable("JoinedTGGroup");
                });

            modelBuilder.Entity("TgBot.TgUserState", b =>
                {
                    b.Property<string>("TgUserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LastUpdateTime")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("StackHead")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WaitingForPayment")
                        .HasColumnType("bit");

                    b.Property<string>("WbcCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TgUserID");

                    b.ToTable("TgUserState");
                });

            modelBuilder.Entity("TgBot.WFDialogItem", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Next")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Removed")
                        .HasColumnType("bit");

                    b.Property<string>("TgUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("WFDialogStack");
                });
#pragma warning restore 612, 618
        }
    }
}
