// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TgBot.SocialLedger;

namespace TgBot.MigrationsPostgres.SocialLedger
{
    [DbContext(typeof(SocialLedgerDb))]
    partial class SocialLedgerDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TgBot.SocialLedger.LedgerPair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("AcceptedOn")
                        .HasColumnType("bigint");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedOn")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeclinedOn")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("UserOne")
                        .HasColumnType("text");

                    b.Property<string>("UserTwo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LedgerPair");
                });

            modelBuilder.Entity("TgBot.SocialLedger.SLTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long?>("ApprovedOn")
                        .HasColumnType("bigint");

                    b.Property<string>("CancelMessage")
                        .HasColumnType("text");

                    b.Property<long?>("CanceledOn")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("DeclineMessage")
                        .HasColumnType("text");

                    b.Property<long?>("DeclinedOn")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("ResendMesasage")
                        .HasColumnType("text");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("TgBot.SocialLedger.SLTransactionPictures", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("ImgeMime")
                        .HasColumnType("text");

                    b.Property<string>("LinkedImage")
                        .HasColumnType("text");

                    b.Property<string>("LinkedImageType")
                        .HasColumnType("text");

                    b.Property<int>("OrderN")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TransactionPicture");
                });

            modelBuilder.Entity("TgBot.SocialLedger.TransactionCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "USD"
                        },
                        new
                        {
                            Id = 2,
                            Name = "EUR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Birr"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
