// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TgBot.SmartLedger;

namespace TgBot.MigrationsPostgres.TgBotCore
{
    [DbContext(typeof(TgBotDb))]
    partial class TgBotDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TgBot.SmartLedger.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Operation")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentRecord")
                        .HasColumnType("uuid");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditRecord");
                });

            modelBuilder.Entity("TgBot.SmartLedger.CashEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<Guid?>("TransactionHead")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CashEntity");
                });

            modelBuilder.Entity("TgBot.SmartLedger.MisDelta", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("DataType")
                        .HasColumnType("text");

                    b.Property<long>("RecordNo")
                        .HasColumnType("bigint");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("AuditId");

                    b.ToTable("MisDelta");
                });

            modelBuilder.Entity("TgBot.SmartLedger.MisUserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("Permitted")
                        .HasColumnType("boolean");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("MisUserProfile");
                });

            modelBuilder.Entity("TgBot.Workflow.WorkFlowInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("WorkItemHead")
                        .HasColumnType("uuid");

                    b.Property<long?>("WorkItemHeadTime")
                        .HasColumnType("bigint");

                    b.Property<int?>("WorkItemHeadType")
                        .HasColumnType("integer");

                    b.Property<int>("WorkType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkFlowMain");
                });

            modelBuilder.Entity("TgBot.Workflow.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("PrevItem")
                        .HasColumnType("uuid");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkFlowId")
                        .HasColumnType("uuid");

                    b.Property<int>("WorkType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkItem");
                });
#pragma warning restore 612, 618
        }
    }
}
