// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TgBot.WeTicket;

namespace TgBot.MigrationsPostgres.WeTicket
{
    [DbContext(typeof(WeTicketDb))]
    partial class WeTicketDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TgBot.WeTicket.BoughtTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentID")
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<bool>("Anonymous")
                        .HasColumnType("boolean");

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer");

                    b.Property<Guid>("FundRaiserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PaymentCode")
                        .HasColumnType("text");

                    b.Property<bool>("RegisteredAgent")
                        .HasColumnType("boolean");

                    b.Property<int>("SerialNo")
                        .HasColumnType("integer");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BoughtTicket");
                });

            modelBuilder.Entity("TgBot.WeTicket.FundAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FundAgent");
                });

            modelBuilder.Entity("TgBot.WeTicket.FundAgentId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer");

                    b.Property<string>("IdInChannel")
                        .HasColumnType("text");

                    b.Property<string>("NameInChannel")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FundAgentId");
                });

            modelBuilder.Entity("TgBot.WeTicket.FundRaiserPictureItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExternalStorageType")
                        .HasColumnType("integer");

                    b.Property<Guid>("FundRaiserID")
                        .HasColumnType("uuid");

                    b.Property<string>("IdInExternalStorage")
                        .HasColumnType("text");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("bytea");

                    b.Property<string>("PictureMIME")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FundRaiserPictureItem");
                });

            modelBuilder.Entity("TgBot.WeTicket.FundRaisingChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FundRaisingChannel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Telegram"
                        });
                });

            modelBuilder.Entity("TgBot.WeTicket.TansferPicture", b =>
                {
                    b.Property<Guid>("WithdrawalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExternalStorageType")
                        .HasColumnType("integer");

                    b.Property<string>("IdInExternalStorage")
                        .HasColumnType("text");

                    b.Property<byte[]>("TransferPicture")
                        .HasColumnType("bytea");

                    b.Property<string>("TransferPictureMime")
                        .HasColumnType("text");

                    b.HasKey("WithdrawalId");

                    b.ToTable("TansferPicture");
                });

            modelBuilder.Entity("TgBot.WeTicket.TicketCompaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentID")
                        .HasColumnType("uuid");

                    b.Property<long>("AutoCloseTime")
                        .HasColumnType("bigint");

                    b.Property<int>("ChannelID")
                        .HasColumnType("integer");

                    b.Property<long>("CloseTime")
                        .HasColumnType("bigint");

                    b.Property<int>("CommissionOutTenThousand")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTickets")
                        .HasColumnType("integer");

                    b.Property<int>("RegistrationFee")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TicketPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TicketCompaign");
                });

            modelBuilder.Entity("TgBot.WeTicket.WithDrawalBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WithdrawalBanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Commercial Bank of Ethiopia",
                            Order = 1
                        });
                });

            modelBuilder.Entity("TgBot.WeTicket.WithDrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<string>("AccountNo")
                        .HasColumnType("text");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("ApprovalNote")
                        .HasColumnType("text");

                    b.Property<long>("ApprovedDate")
                        .HasColumnType("bigint");

                    b.Property<int>("BankId")
                        .HasColumnType("integer");

                    b.Property<long>("Comission")
                        .HasColumnType("bigint");

                    b.Property<Guid>("FundRaiserId")
                        .HasColumnType("uuid");

                    b.Property<long>("RegistrationFee")
                        .HasColumnType("bigint");

                    b.Property<long>("RejectDate")
                        .HasColumnType("bigint");

                    b.Property<string>("RejectNote")
                        .HasColumnType("text");

                    b.Property<long>("RequestDate")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestNote")
                        .HasColumnType("text");

                    b.Property<string>("TransferRefernce")
                        .HasColumnType("text");

                    b.Property<long>("TransferedAmount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("WithDrawalRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
